apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0" # deploy first
spec:
  project: default
  source:
    repoURL: https://github.com/michealken30/loan-app-config
    targetRevision: main
    path: kyverno/policies # folder containing all 10 YAMLs
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno # or default namespace if policies are cluster-wide
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

#
